const actionTypes = {
  CLEAR_LEVEL: "CLEAR_LEVEL",
  PROMPT: "PROMPT",
  UPDATE_SHIP: "UPDATE_SHIP",
  UPDATE_PLANETS: "UPDATE_PLANETS",
  INCREMENT_CLOCK: "INCREMENT_CLOCK",
  SELECT_LEVEL: "SELECT_LEVEL",
  UNSET_GAME: "UNSET_GAME",
  RESET_GAME: "RESET_GAME",
  START_GAME: "START_GAME",
  STOP_GAME: "STOP_GAME"
};

export default actionTypes;
